### ISSUE TITLE
Can't run on windows 7

### ISSUE THREAD

**Issue by GellertBorsay** [Vulpovile/G3D-Fun#28]
I hope you'll see this.
So, I've seen my friends use it and telled me to try it.
So, I used my (only) laptop, that ran windows 7.
An error message popped up: The application has failed beacuse its side-by-side configuration is incorrect.
I tried to troubleshoot and this message was the result:
Incompatible application

**Comment by willemsteller** [comment]
Do you have Microsoft Visual C++ 2005 Redistributable Package installed?
https://www.microsoft.com/en-us/download/details.aspx?id=3387

**Comment by Vulpovile** [comment]
It's DEVELOPED on 7, so i'm pretty sure you're just missing the VC 2005 redist
It even works on windows 98!
