### ISSUE TITLE
Incorrect settings?

### ISSUE THREAD

**Issue by MaximoBP** [Vulpovile/G3D-Fun#29]
When i try to open the game on windows XP it just says that the app launched with the incorrect settings orsomething like that and that reinstalling the game should fix it,i did it and nothing happened,it gives me the same error everytime,and yes i have VC 2005 redist and Microsoft Visual C++ 2005 Redistributable Package

**Comment by Vulpovile** [comment]
you must have both x86 and x64 versions of it. You must use the SP1 with MFC patches!
