### ISSUE TITLE
how am i supposed to even use this

### ISSUE THREAD

**Issue by mnuggdanugg** [Vulpovile/G3D-Fun#41]
so, i open G3DTest.exe, and it asks me for a rbxl file, but i do not have any pre-2013 rbxl files. and if i don't open an .rbxl file it just doesn't work, the gui is irresponsive and when i try to choose a model, it says "404 not found"

**Comment by mnuggdanugg** [comment]
and even if i got a rbxl file that i can open, i can't play.

**Comment by mnuggdanugg** [comment]
it would help to have a manual or something like that

**Comment by DirtPiper** [comment]
The GUI isn't responsive because hardly any of it is implemented yet. This is an extreme alpha, it is not intended to be used beyond simple bug testing.

**Comment by mnuggdanugg** [comment]
oh ok
