### ISSUE TITLE
Requires instructions

### ISSUE THREAD

**Issue by oofnack** [Vulpovile/G3D-Fun#42]
i don`t know how to get this working.
also needs to add support for people not using WinRAR .

**Comment by willemsteller** [comment]
Hi there!
You can download the latest release at the releases page (https://github.com/Vulpovile/G3D-Fun/releases) and extract it using any extraction tool which supports .7z files (I'd suggest 7zip or WinRAR).
If you're getting a side-to-side configuration error, please download the Visual C++ 2005 redistributable (http://web.archive.org/web/20180216150123if_/https://download.microsoft.com/download/d/3/4/d342efa6-3266-4157-a2ec-5174867be706/vcredist_x86.exe)

If you're still having problems please let us know!

**Comment by oofnack** [comment]
is there a way to open it in a folder because it came out like a folder.
also does windows 10 support 7z

**Comment by Vulpovile** [comment]
There are now official [releases](https://github.com/Vulpovile/G3D-Fun/releases) with installers. Please let me know if it does not work by reopening this issue.
