### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by armanium82** [Vulpovile/G3D-Fun#47]
i would be happier with a pre compiled version, or at least instructions on how to compile it

**Comment by willemsteller** [comment]
You can find pre-compiled versions in the [releases section](https://github.com/Vulpovile/G3D-Fun/releases)

**Comment by starfrost013** [comment]
tbh, we could probably have CI if we wanted.

**Comment by armanium82** [comment]
> You can find pre-compiled versions in the [releases section](https://github.com/Vulpovile/G3D-Fun/releases)

the newest one isnt there

**Comment by Vulpovile** [comment]
Resolved in newest release
