### ISSUE TITLE
Any way to compile on modern VS (2019)?

### ISSUE THREAD

**Issue by TsunamiWind** [Vulpovile/G3D-Fun#49]
Please tell me.

**Comment by Vulpovile** [comment]
Not officially, and not recommended. You'd need to rebuild all the libraries.

**Comment by TsunamiWind** [comment]
> Not officially, and not recommended. You'd need to rebuild all the libraries.

Ok, but do I use VS 2005 or 2008? And what about the G3DALL.h error?

**Comment by peisredman** [comment]
Retard just use vs 2005
