### ISSUE TITLE
Any quickstart guide/tutorial on setting the dependencies up?

### ISSUE THREAD

**Issue by tijon1** [Vulpovile/G3D-Fun#51]
self-explanatory.

**Comment by tijon1** [comment]
nvm, figured it out myself
1.Download SDL from this link [https://www.libsdl.org/release/SDL-devel-1.2.15-VC.zip](url)

2.Download G3D 6.10 from this link [https://sourceforge.net/projects/g3d/files/g3d-cpp/6.10/g3d-6_10.zip/download](url)

3.Put these two into the root directory of G3D-Fun

4.Open up the project in 2005-2008 Visual Studio (with C++ compiler and tools installed)

5.Right click on the project and click on properties.

6.Go to C/C++ and open up Additional Include Directories (using that right .. button)
Add ".\SDL-1.2.15\include" and add ".\g3d-6_10\include" (assuming you have put these two into the root directory of G3D-Fun
Click on Ok

7.Go to Linker/General and open up Additional Library directories (using that right .. button)
Add ".\SDL-1.2.15\lib\x86" and add ".\g3d-6_10\win32-vc8-lib" and click on Ok.

8.Close the properties and try compiling. It should take a few minutes but it should complete with 0 errors and a few warnings (nothing to worry about)

**Comment by ElCapor** [comment]
hey thanks really great i will test out , is there a way to contact yuou trough discord ?

**Comment by tijon1** [comment]
> hey thanks really great i will test out , is there a way to contact yuou trough discord ?
I will private message you and yes, I do have a discord.

**Comment by brannanz** [comment]
Got an ERROR LNK2001: unresolved external symbol __imp__RegCloseKey@4, et cetera. Using visual studio 2005 express edition, windows xp pro.

**Comment by tijon1** [comment]
> Got an ERROR LNK2001: unresolved external symbol __imp__RegCloseKey@4, et cetera. Using visual studio 2005 express edition, windows xp pro.

Try adding Advapi32.lib to Linker -> Input -> Additional Dependencies for all of the project configurations.

**Comment by brannanz** [comment]
Didn't seem to fix it... I'm using the Windows SDK v6.1

**Comment by brannanz** [comment]
NOTE: Open Dynamics Engine 0.6 is now needed.
https://sourceforge.net/projects/opende/files/ODE/0.6/
You can get it here.

**Comment by brannanz** [comment]
I got it to compile, but on launch it just craps out and gives me this error:
![image](https://user-images.githubusercontent.com/76947244/204141163-a8533946-2fa6-448f-94a3-819cd7f12c18.png)
Must be some DLL linking error.

EDIT:
The problem was compiling in Debug mode.

**Comment by tijon1** [comment]
> I got it to compile, but on launch it just craps out and gives me this error: ![image](https://user-images.githubusercontent.com/76947244/204141163-a8533946-2fa6-448f-94a3-819cd7f12c18.png) Must be some DLL linking error.

Try installing Microsoft Visual C++ Redistributable Packages 2003, 2005, and 2008. You could also be linking the program with debug or release DLLs. Use the correct DLLs, debug libraries if you compiled as debug, release libraries if you compiled as release.
