### ISSUE TITLE
Duplicate Game Instance

### ISSUE THREAD

**Issue by Boalbads** [Vulpovile/G3D-Fun#62]
You are able to duplicate the game instance, causing some issues, to perform this, once you open G3D Fun, press Duplicate and then the Property grid will change, allowing you to see the what is inside the game.
![image](https://user-images.githubusercontent.com/68003904/193619861-27519b3f-493d-4ee3-a9f0-ca36e784e106.png)

**Comment by Vulpovile** [comment]
I'm not able to do this... how did you manage that?

**Comment by Boalbads** [comment]
My only ideas on how it could be reproduced is either if the bug somehow reappears, or if you change it so that duplicate can be pressed with nothing selected.

**Comment by Boalbads** [comment]
Was just able to recreate it, gonna try find a constant method how, but if you want some pictures of it I can send them

**Comment by Boalbads** [comment]
And I managed to crash it...

**Comment by Vulpovile** [comment]
> 
To be honest, that's nothing new, we're still working on the stability of it lol

**Comment by Boalbads** [comment]
Lol

**Comment by Boalbads** [comment]
Recreated it, I think I know how to do it, trying again now

**Comment by Boalbads** [comment]
> Recreated it, I think I know how to do it, trying again now

When you select one of the items, it shows this (just the name, but you are able to delete, group, ungroup, and duplicate it. (also my recreation attempt failed, gonna keep trying to find out how I did it)
![image](https://user-images.githubusercontent.com/68003904/193629809-ecda2782-bfdf-4491-8b0b-0146bb9d8818.png)

**Comment by Boalbads** [comment]
I think i've recreated it consistantly,
Select a Part
Duplicate it
Press Go
Press Stop
Rename Part
Open a new place
Open the dropdown to select part
Select the part you renamed
You have now recreated Default Game Instance

**Comment by Vulpovile** [comment]
Reproduced, also seems like a possible ACE vulnerability. Really need to replace that stupid selection system
