### ISSUE TITLE
Crash when duplicating block that doesn't exist

### ISSUE THREAD

**Issue by Boalbads** [Vulpovile/G3D-Fun#67]
Place motor on a block, press Go, Press Stop, Make a new place, you can still use group, ungroup, duplicate and delete, pressing duplicate will crash the game

**Comment by Vulpovile** [comment]
Confirmed. Many of these issues are part of the currently downright awful method of selection. When I have time I'll mark which ones and maybe link them all to a single issue (or just fix them all)
