### ISSUE TITLE
Anchored parts in a place file are not anchored when loading

### ISSUE THREAD

**Issue by thecssdoom** [Vulpovile/G3D-Fun#71]
Self explanatory

**Comment by Modnark** [comment]
Weird, I thought we fixed this? Are you downloading the correct release?

**Comment by Vulpovile** [comment]
Please attach the place file, this does not happen on any we have

**Comment by Modnark** [comment]
> Please attach the place file, this does not happen on any we have

Oh, right, it might be something to do with alphabetical casing, I believe we just check of "anchored"

**Comment by thecssdoom** [comment]
https://cdn.discordapp.com/attachments/862154953295396884/1026617632113315850/plinko.rbxl

**Comment by thecssdoom** [comment]
Note : place file created with 2007M client

**Comment by Modnark** [comment]
only one part falls for me because it's not anchored at all, everything else is fine

**Comment by thecssdoom** [comment]
Must be because of an older version of the repo i used.
